### PR TITLE
created user account crud

### PR DESCRIPTION
**Pull request by RachaelKlein92**
I've created and added the following:
1.) An Implementation of an Interface UserAccount Respository
2.) Created standard Interface
3.) Interface UserAccount Respository
4.) A UserAccount Repository Implementation using Test Driven Development

### CODE REVIEW

**Comment by Bradonic** [comment]
Code looks good and consists of no errors

**Comment by Bradonic** [comment]
Code looks good and consists of no errors

**Review by Bradonic — APPROVED** [review]
Code looks good and consists of no errors

**Comment by RachaelKlein92** [comment]
Domain Driven Design - Repository Section about to begin now.

**Pull request merged**
